
baseURL = "https://printnow99.github.io/"
languageCode = "en-us"
title = "PrintNow Digital Printing"
theme = "basic"
defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  description = "Blog cetak digital: banner, brosur, proposal, dan lainnya - PrintNow.web.id"

[outputs]
  home = ["HTML", "RSS", "JSON"]
